### ISSUE TITLE
Configuration management

### ISSUE THREAD

**Issue by crookm** [crookm/InterFlare#4]
Ability to configure accounts using a username and password. Focusing on Instagram for now, but should allow for any kind of social network in the future.

The likes of Instagram will be a username/password in plain text for now, because they don't offer reasonable API access. Twitter will be an oauth token.

Should could be an embedded SQLite DB, but a static config.json could be fine too. Of course this will change later, if that's the case.

**Acceptance criteria**:
- [x] Ability to add authentication information for multiple accounts and providers.
- [x] Ability to update authentication information for each account.
- [x] Ability to remove authentication information.
- [x] Information should be stored in EITHER SQLite embedded DB or a static config file.

**Comment by crookm** [comment]
@youngseebi is this what you imaged with the accounts thing?

**Comment by al5ina5** [comment]
Flawless.

**Comment by al5ina5** [comment]
I'm under the impression I shouldn't worry about the plain-text pads since the app will run locally...is this correct?

**Comment by crookm** [comment]
Yea but it's bad practice, future worry atm though

**Comment by al5ina5** [comment]
I'm aware. Great!

**Comment by crookm** [comment]
🎉  finally haha
